export const [GET_ALL_PROJECT_SAGA, SET_PROJECT_LIST] = ["GET_ALL_PROJECT_SAGA", "SET_PROJECT_LIST"];
export const DELETE_PROJECT_SAGA = "DELETE_PROJECT_SAGA";
export const REMOVE_USER_FROM_PROJECT_SAGA = "REMOVE_USER_FROM_PROJECT_SAGA";